FROM mysql:8.0

ENV MYSQL_ROOT_PASSWORD=root

VOLUME ["/var/lib/mysql"]

COPY a_crear_bd.sql /docker-entrypoint-initdb.d/
COPY b_crear_tablas.sql /docker-entrypoint-initdb.d/
COPY c_crear_relaciones.sql /docker-entrypoint-initdb.d/
COPY d_insertar_datos.sql /docker-entrypoint-initdb.d/

EXPOSE 3306